//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcMusicStore.Models
{
    using System;
    
    public partial class lstOrderDetails
    {
        public int OrderDetailId { get; set; }
        public int OrderId { get; set; }
        public string Album { get; set; }
        public int Quantity { get; set; }
        public decimal UnitPrice { get; set; }
    }
}
