//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcMusicStore.Models
{
    using System;
    
    public partial class lstStoreManager
    {
        public int AlbumId { get; set; }
        public string TitleAlbum { get; set; }
        public string Artist { get; set; }
        public string Genre { get; set; }
        public decimal PriceAlbum { get; set; }
        public string AlbumArtUrl { get; set; }
    }
}
